### ISSUE TITLE
Add CI 

### ISSUE THREAD

**Issue by matthewfeickert** [iml-wg/cwp#2]
- [x] Create a [CircleCI](https://circleci.com) account for the IML (@omazapa can you do this as you have general admin privileges?)
- [x] Setup web area to push to after build
- [x] Write `config.yml` using [LaTeX-Docker](https://hub.docker.com/r/matthewfeickert/latex-docker/) ([Example](https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template/blob/master/.circleci/config.yml))

The idea is to setup a CI system to make sure that everything is still building as expected (c.f. [here](https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template) for an example of this in action)

**Comment by omazapa** [comment]
Hi @matthewfeickert 

the account in circleci  https://circleci.com/setup-project/gh/iml-wg/cwp

**Comment by matthewfeickert** [comment]
Thanks @omazapa, that's great news.

@SergeiML, is there an IML controlled web area on CERN's servers that we can have the CI deploy to?

**Comment by matthewfeickert** [comment]
@omazapa @SergeiML As soon as we can get a web area on a server that will be publicly accessible from the web then we should have everything fully setup for doing the revisions to finish the CWP. Do you have suggestions on who how we can get that web area setup?

**Comment by omazapa** [comment]
Hi @matthewfeickert  en travisci you dont need a server for the ci deploy, they can provide a free virtual machine with docker for that.

**Comment by matthewfeickert** [comment]
@omazapa Maybe I don't understand what you mean, but I am just saying that it would be nice to setup a web accessible location to deploy the version of the CWP that the CI builds _to_. As an example of what I mean, I am [hosting the built pdfs of my department's Ph.D. template on my personal webspace](https://www.physics.smu.edu/mfeickert/dedman-thesis-latex-template/template.pdf) and [the CI deploys it to there](https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template/blob/master/.circleci/config.yml#L38).

The reason that I'm suggesting CircleCI instead of Travis is that with Circle you can choose to use a Docker image other then one they supply, while using non-Travis images is a huge pain (I've only ever figured out how to deal with this by pulling the image I want to use into Travis and then running `docker exec` commands in the Travis CI). As I already have a Docker image with TeX Live 2017 installed in it, it seems a lot easier to just use that then to have Travis install LaTeX on their Trusty image every build.

**Comment by omazapa** [comment]
@matthewfeickert  ahhh ok, 
we can put the pdf on http://iml.web.cern.ch or http://oproject.org what do you think @SergeiML?

**Comment by omazapa** [comment]
Hi @matthewfeickert 
 to do an automatic process I will give you access to the oproject repository https://github.com/oprojects/oprojects.github.io
in your CI system is just to clone it and put the the new pdf with the name ml-cwp.pdf in the folder 
https://github.com/oprojects/oprojects.github.io/tree/master/cwp/

commit and push it and automatically github pages will update it in 
http://oproject.org/cwp/

Cheers,
Omar.

**Comment by matthewfeickert** [comment]
@omazapa Sorry for the late follow up (have been travelling). This all sounds good. My only question is if you have suggestions on how to properly add authentication keys to do the cloning and pushing. That is, do you have a suggestion of how to add a hashed key into the CI (something along the lines of [this](https://github.com/diana-hep/pyhf/blob/master/.travis.yml#L26-L28), which seems like the better option then having secret variables that are full ssh keys stored in the project settings on GitHub)?

**Comment by matthewfeickert** [comment]
@omazapa Actually, I guess [CircleCI has docs for this](https://circleci.com/docs/2.0/gh-bb-integration/#creating-a-github-user-key). Given that you have admin controls for the [oprojects.github.io repo](https://github.com/oprojects/oprojects.github.io) can you add a deploy key to it following those instructions, and then just let me know what the fingerprint is (or maybe you can do all of this just through the [CircleCI interface](https://circleci.com/docs/2.0/configuration-reference/#add_ssh_keys)? --- not sure)?

**Comment by omazapa** [comment]
Hi @matthewfeickert 
you can to add a new ssh to your account, and I should work for oproject because you have permissions.
but anyway I added you like admin.

**Comment by matthewfeickert** [comment]
@omazapa Okay [this seems to work](https://github.com/oprojects/oprojects.github.io/commit/64cf5281a8ad8c36f9190d9bcf2aeb09b350a890). However, doing things this way is going to result in _a lot_ of commits to the oprojects.github.io repo, which would essentially pollute the commit history. 

I am going to try to see if I can figure out a way when the CI runs on a PR for the CWP if it can then create a PR for the oprojects.github.io repo or add a commit to an existing PR for the oprojects.github.io repo.

**Comment by matthewfeickert** [comment]
@omazapa @SergeiML To avoid the concerns I had with polluting the OProject Git repo history I've created a CERN internal web area on my EOS space (it used to be all ATLAS internal) that the CI now deploys to:

https://cern.ch/feickert/IML-CWP/

For the time being when we are still doing lots of revisions we can use this area, and then once we've settled down into the final stages we can switch the CI deployment back to OProject's webpage. I've detailed what will need to be done in the future in Issue #6.
