### ISSUE TITLE
 author list

### ISSUE THREAD

**Issue by omazapa** [iml-wg/cwp#5]
Dear Matthew
* Basically right now it displays multiple affiliations (1 author - 1 affiliation) while it would be better to have people from same affiliation (for example CERN or Fermilab) have the same index so that they don't appear many times.
* Sort the index values for authors in the new schema.

Thank you!

**Comment by matthewfeickert** [comment]
So I have a WIP (so please don't merge it yet) PR open at the moment that has at least a proposal to a solution implemented.

It is probably most clear to see what is happening by looking at the introduction of "settables" in [`src/affiliations.tex`](https://github.com/iml-wg/cwp/pull/7/files#diff-edfeefcc22d8923b0057c44608645834), then how the are used in this first commit example in the diff of [`src/authors.tex`](https://github.com/iml-wg/cwp/pull/7/files#diff-b33354a8ec05d230f3de311e8d90c159).

The "settable" acts as a variable to replace itself inline with the value it was set to. It operates in a similar manner as the relationship to dict keys and values in Python. You can see this in action by looking at [PR draft 7](https://feickert.web.cern.ch/feickert/IML-CWP/PRs/draft_ml-cwp_PR7.pdf) --- note Sauers and Duarte are both properly affiliated to Fermilab now, which only appears in the affiliations list once.

> Sort the index values for authors in the new schema.

@omazapa @SergeiML If this is an okay solution for now, then the next question is what is the ordering that things will be numbered by? Alphabetical ordering of authors? Or by institution?

**Comment by matthewfeickert** [comment]
> If this is an okay solution for now, then the next question is what is the ordering that things will be numbered by? Alphabetical ordering of authors? Or by institution?

To follow up on this: Sergei said that this should be done by author last name.

@omazapa @SergeiML 

At the moment the way the author list is printed is first name, last name

> Sergei, Gleyzer<sup>28</sup>

It seems a bit weird to me that the comma is there. Was this intentional? Or should we instead do last name, first name?

> Gleyzer, Sergei<sup>28</sup>

**Comment by matthewfeickert** [comment]
@omazapa @SergeiML 

To try and deal with the author list quickly I stopped working on a pure LaTeX approach and wrote some quick and dumb Python to take care of it by generating an author list at build time from a CSV. Let me know if you have any concerns RE: this.

Additionally while I was going through it seems that there are still some unlisted author affiliations, which at the [moment you can see as](https://feickert.web.cern.ch/feickert/IML-CWP/PRs/draft_ml-cwp_PR7.pdf)
> <sup>9</sup> unlisted

Do we have these individuals emails to get affiliations for them?

**Comment by matthewfeickert** [comment]
@omazapa It seems that there are only 72 institutions on the current draft on ShareLaTeX but yet I have 74 in the output of PR #7. Do you know where the difference comes from? Were some authors removed?

**Comment by matthewfeickert** [comment]
> It seems that there are only 72 institutions on the current draft on ShareLaTeX but yet I have 74 in the output of PR #7.

@omazapa @SergeiML This is fixed now. There were hyphens in an entry for Max Planck and LIP Lisboa. 72 on both now. :+1:
