### ISSUE TITLE
Harmonize ShareLaTeX and GitHub

### ISSUE THREAD

**Issue by matthewfeickert** [iml-wg/cwp#8]
@SergeiML has pointed out there are now discrepancies in the ShareLaTeX version (which has continued to be updated?) and the GitHub version.

- participants.tex (updated by Omar, same authors you have already)
- applications.tex (empty reference 2 removed)
- main.tex (added abstract and conclusions)
- conclusions.tex (new file)
- roadmap.tex (updated text)

These will need to get harmonized in a PR after PR #7 is completed.

**Comment by omazapa** [comment]
Hi @matthewfeickert 
Yes, some updates was made in the document in sharelatex,
* Abstract
* Authors
* Some sections also have some modifications from Sergei and Harrison.
* Removed bad citation.

I think that we can  take the sources from ShareLatex  and upload it to github, 
what do you think?

Cheers,
Omar.

**Comment by matthewfeickert** [comment]
@omazapa Directly, no, the structure is changed a bit, so it won't build out of the box if you do a direct dump. I can make a PR for this that actually gets the diffs once we understand how the author list has changed so that there isn't duplication of work from PR #7. Given that, do you have thoughts on [this comment in Issue #5](https://github.com/iml-wg/cwp/issues/5#issuecomment-401639980)?
